version: '3.9'

services:

  nginx-waf:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: "80"
      SSL_PORT: "443"
      DNS_SERVER: "1.1.1.1"
      METRICS_ALLOW_FROM: all
    ports:
      - "80:80"
      - "443:443"
    # If you need to modify nginx config, mount your volume as the template file
    # volumes:
    #  - ./nginx/nginx.conf:/etc/nginx/templates/nginx.conf.template:rw
  